### ISSUE TITLE
Applying for SFG Author

### ISSUE THREAD

**Issue by shamsid** [spring-framework-guru/sfg-blog-posts#100]
**Shamsher Ahmed**

**Hi, my name is Shamsher and I’m currently a software developer at nFactorial Analytical Sciences. I learned lot through blogs and online resources so i want to give it back through sharing and as a SFG author i will able to reach massive audience.**
****Please consider my application for author****

**https://www.linkedin.com/in/shamsid/**

**Comment by ximanta** [comment]
Hi Azhwani, 

Please share your email-ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks
Ximanta
