### ISSUE TITLE
Applying for SFG Author

### ISSUE THREAD

**Issue by azhwani** [spring-framework-guru/sfg-blog-posts#107]
Hey SFG,

My name is Azhwani, a software engineer by profession and passion! I regularly read your posts and I just wanted to reach out because I have really been enjoying your writing.

I know you are busy, so I won't waste your time. I believe that I can add value to your audience, so I'm reaching out because I'd love to contribute in spreading knowledge through your blog. 

Thanks for your time and consideration! I can't wait to hear back from you.

[https://www.linkedin.com/in/abderrahim-azhrioun](https://www.linkedin.com/in/abderrahim-azhrioun)

Cheers,
Stay safe!

**Comment by ximanta** [comment]
Hi Azhwani, 

Please share your email-ID to take this forward.

Thanks
Ximanta
