### ISSUE TITLE
Request for Blogging at Spring Framework Guru !

### ISSUE THREAD

**Issue by saurabhchaturvedy** [spring-framework-guru/sfg-blog-posts#109]
**Saurabh Chaturvedi:**

**I am from India . I work as a Senior Software Developer  . I have 6.5 years of experience in Java/Spring/Spring-Boot development . I stumbled upon your blog after taking a couple of courses by you at Udemy  (Apache Maven & Spring Boot Testing) Beginner to Guru series . With my experience in Software Development , i also feel a need & passion to blog about new things happening around Spring frameworks or just telling the concepts in a much better way for people to understand . And i feel SFG is the best platform for that . Waiting for your reply :**

**https://www.linkedin.com/in/saurabh-chaturvedi-473a4251/**

**Comment by ximanta** [comment]
Hi Saurav, 

Please share your email-ID to take this forward.

Thanks
Ximanta
