### ISSUE TITLE
Ankur Shukla - New Author Request

### ISSUE THREAD

**Issue by ankurongit** [spring-framework-guru/sfg-blog-posts#113]
Ankur Shukla

Hi, I am Ankur. I am a software developer by profession, I have 6 years of total work experience.
I started my Spring Framework journey last year and enrolled in your courses. I used the courses as a cookbook and refer the topics as and when needed.
I wish to contribute by writing blog posts so that I can enable other learners.
Below is my Linkedin profile:
https://www.linkedin.com/in/ankurshu10/

**Comment by ximanta** [comment]
Hi Ankur,

Please share your email-ID to take this forward.

Thanks
Ximanta

**Comment by ankurongit** [comment]
Hi, 
You can reach me at ankurshu@hotmail.com.

Thanks,
Ankur Shukla.
