### ISSUE TITLE
[POST] - Spring RestTemplate with HTTPClient

### ISSUE THREAD

**Issue by springframeworkguru** [spring-framework-guru/sfg-blog-posts#14]
Show how to configure Spring RestTemplate and how to configure Apache HTTP client

**Comment by Waginator** [comment]
I have created two blog posts about this:
- Using RestTemplate in Spring
- Using RestTemplate with Apaches HttpClient

I only have to deal with translation.

**Comment by Waginator** [comment]
Done!
