### ISSUE TITLE
[POST] - Spring External Properties

### ISSUE THREAD

**Issue by springframeworkguru** [spring-framework-guru/sfg-blog-posts#2]
General overview of using external properties. Include setting properties, SPEL, profiles. Use current best practices w/Spring Boot. 

See: https://docs.spring.io/spring-boot/docs/2.2.0.M2/reference/html/spring-boot-features.html#boot-features-external-config

**Comment by ximanta** [comment]
Reassigned as no work in progress.

**Comment by maureenCindy** [comment]
Hie Ximanta,

I am resuming work.

**Comment by maureenCindy** [comment]
The code has been merged and the article has been published.
