### ISSUE TITLE
Apply Guest Author - Mauricio Ledesma

### ISSUE THREAD

**Issue by mledesmac** [spring-framework-guru/sfg-blog-posts#31]
**Your name:** Mauricio Eduardo Ledesma Cortés

**Introduce yourself:**
Im from Mexico City, i love to understand how the things works, in this case java spring, and i always try to help other persons to understand the advantages of framework.

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/mledesmac

**Comment by springframeworkguru** [comment]
Hi Mauricio! Just connected with you on LinkedIn - pls message me there. Thanks!

**Comment by mledesmac** [comment]
Hi @springframeworkguru , i don't have any problem to write a small example if is need it.
