### ISSUE TITLE
SFG Author Application - Priyank Srivastava

### ISSUE THREAD

**Issue by priyank-sriv** [spring-framework-guru/sfg-blog-posts#32]
**Your name**
Priyank Srivastava

**Introduce yourself**
I'm a backend developer with over 6 years of professional experience. I am based out of Pune, India. 
I enjoy solving problems, small or big. I have spent copious amounts of time digging myself into a hole, and working my way out. I make an honest effort to write maintainable and extendable code, and keep learning better ways to solve a problem.

Technical skills:
 -  My core strengths are Java and Spring/Spring-boot/Spring-cloud. 
 -  I'm fairly comfortable with messaging middleware such as RabbitMQ and Kafka; SQL databases such as MySQL, Postgres; build tools Maven and Gradle.
 - I've also dabbled in MongoDB; JMH benchmarking; serialization protocols such as Avro, ProtoBuf and (of course) Json
 - Currently, I'm learning reactive streams and new Java features after version 8.

I've joined and been active on stackoverflow over the past month, for reference: [answers](https://stackoverflow.com/users/6886283/sindbad90?tab=answers&sort=newest)

**Link to your LinkedIn Profile**
http://linkedin.com/in/sriv-priyank/

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please follow up with me there - thanks!

**Comment by priyank-sriv** [comment]
Great!
