### ISSUE TITLE
SFG Author Application - Damian Sniatecki

### ISSUE THREAD

**Issue by DSniatecki** [spring-framework-guru/sfg-blog-posts#33]
Damian Śniatecki

I am a big fan of the modern Spring framework and Java. I also know the basics of C / C++ / assembler. In the near future I'm also going to start learning Scala. The most important for me in programming is readability and simplicity. I think I can give much valuable knowledge to the others.

https://www.linkedin.com/in/dsniatecki/

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please message me there.
