### ISSUE TITLE
Namasivayam

### ISSUE THREAD

**Issue by namasivayam-G** [spring-framework-guru/sfg-blog-posts#35]
Namasivayam G

A Programmer who have 4 plus experience in Java J2EE and frameworks like spring, hibernate, spring boot and Front end frameworks like angular. Have work experience with most reputed Indian IT companies like Tata consultancy services, HCL as full time programmer.

https://www.linkedin.com/in/namasivaayam-g-b67067a3

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please message me there.
