### ISSUE TITLE
SFG Guest Author Application - Daniel Wagner

### ISSUE THREAD

**Issue by Waginator** [spring-framework-guru/sfg-blog-posts#36]
**Your name** 
Daniel

**Introduce yourself**
My name is Daniel and I'm a passionate Java developer. I'm from Germany and have been working for more than 5 years at LucaNet AG, the manufacturer of the standard software of the same name. LucaNet is a software for controlling, planning and legal group consolidation.

Most of my free time is devoted to training in new and exciting topics that the Java ecosystem has to offer. I mainly use Udemy and private programming projects to apply what I've learned directly in practice.

My main areas of interest are:
- Spring Framework / Spring Boot (particularly MVC, Data, Security and the core stuff like DI and IoC)
- new Java features (Java 8 to 11)
- Algorithms and data structures
- Thymeleaf templating engine
- Angular 

**Link to your LinkedIn Profile**
https://www.linkedin.com/in/daniel-w-9b137a103/

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please message me there.
