### ISSUE TITLE
SFG Author Application 

### ISSUE THREAD

**Issue by maureenCindy** [spring-framework-guru/sfg-blog-posts#37]
**Your name**
Maureen Sindiso Mpofu

**Introduce yourself:**
I am a senior systems development specialist at Econet Wireless Zimbabwe. I am a holder of BSc Honours Degree in Computer Science and I am currently studying a masters in software engineering with the University of Liverpool.I am also a certified  Java SE Professional and  I am a Pivotal certified Spring Core v4.3 Professional. I have vast experience  in developing telecoms , retail and media enterprise applications using spring framework.It would be a great opportunity and an honour for me to be part of the spring framework guru authors.

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/maureen-sindiso-mpofu-98b39468

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please message me there.
