### ISSUE TITLE
SFG Author Application 

### ISSUE THREAD

**Issue by root1** [spring-framework-guru/sfg-blog-posts#38]
**Your name:**
Hopewell Mutanda

**Introduce yourself:**
I am a senior software engineer for Equals, the biggest creddit card company in Zimbabwe. I am a holder of a Bachelors Honors Degree in Computer Science and currently studying for masters in Software Engineering with university of Liverpool. I have the following java certifications:
Oracle Certified Java Professional,
Oracle Certified Expert JPA,
Oracle Certified Expert EJB,
Oracle Certified Expert Web Component,
Oracle Certified Expert Webster vices. 
I have vast experience in the development of Java enterprise applications in banking, retail and insurance industries. I wish to join SFG as an author and I hope my application would be considered. 

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/hopewell-mutanda-4ab42666

**Comment by springframeworkguru** [comment]
Thanks - I connected with you on LinkedIn - please message me there.
