### ISSUE TITLE
SFG Application

### ISSUE THREAD

**Issue by pyteRobert90** [spring-framework-guru/sfg-blog-posts#39]
Robert Militaru

Hi, I am Robert,  I am 30 years old and I am a big fan of spring framework, my experience with spring and java is around 7+ years old. I would like to be an author on spring guru.

Cheers 

https://www.linkedin.com/in/robert-militaru-ba931857/

**Comment by springframeworkguru** [comment]
Hi Robert - I connected with you on LinkedIn - please message me there. Thanks!
