### ISSUE TITLE
[PROPOSAL} -new topic

### ISSUE THREAD

**Issue by pyteRobert90** [spring-framework-guru/sfg-blog-posts#40]
**What Topic Would You Like To Write About:**
Spring DI, What it is and how to use it. ALso best practices

**Target Length:**

1000-2000

**Supporting Links:**

**Comment by springframeworkguru** [comment]
@pyteRobert90  - can you expand on the description? Thanks!

**Comment by pyteRobert90** [comment]
@springframeworkguru  i think this is duplicate with 
https://github.com/spring-framework-guru/sfg-blog-posts/issues/47

So you can delete this. 

Thanks
Robert
