### ISSUE TITLE
[POST] - Debug your Code in IntelliJ

### ISSUE THREAD

**Issue by ximanta** [spring-framework-guru/sfg-blog-posts#41]
Blog with procedural steps with screenshots to demonstrate a debugging use case. 
1500-2500 Words

**Comment by romanczukrobert** [comment]
I will start to work on this if that's ok.

**Comment by ximanta** [comment]
It's fine. Please take up.

**Comment by ximanta** [comment]
Please take this up.

**Comment by ximanta** [comment]
Published at https://springframework.guru/debug-your-code-in-intellij-idea/
