### ISSUE TITLE
[POST] - Dependency Injection in Spring

### ISSUE THREAD

**Issue by ximanta** [spring-framework-guru/sfg-blog-posts#47]
Explain how Spring performs Dependency Injection. Show examples of the different types of DI.
750-1500 Words

**Comment by pyteRobert90** [comment]
i will start working on this.

**Comment by ximanta** [comment]
Post already exists: https://springframework.guru/best-practices-for-dependency-injection-with-spring/
https://springframework.guru/dependency-injection-example-using-spring/
