### ISSUE TITLE
For the position of SFG Author (Paid Contributor)

### ISSUE THREAD

**Issue by vinod827** [spring-framework-guru/sfg-blog-posts#50]
**Vinod Kumar Nair**

I have 11 years of core development experience in Java and have worked in various projects across different industry domains be it government sector, procurement or retail banking. 
I'm certified in both AWS Cloud and Java 8. I'm also a full stack engineer and have worked in ReactJS 16.8, Spring 5, Spring Boot 1.5/2.0, Microservices, Spring Security/OAuth 2.0/JWT and SAP/Pivotal Cloud Foundry. Currently, associated with SAP Labs in India.

Please do check out my profile at:- 

https://www.linkedin.com/in/vinod827/

**Comment by springframeworkguru** [comment]
Hi Vinod - I connected with you on LinkedIn - please message me there. Thanks!

**Comment by vinod827** [comment]
Hi @springframeworkguru ,

Thanks for sending the invite on LinkedIn.
I have sent you the message.

Cheers
