### ISSUE TITLE
Using GraphQL in a SpringBoot application

### ISSUE THREAD

**Issue by vinod827** [spring-framework-guru/sfg-blog-posts#53]
**What Topic Would You Like To Write About:**
Nowadays there is a buzzword called **GraphQL**. Technology is shifting towards GraphQL over REST API's. I would like to write an article for implementing GraphQL in a SpringBoot application and later demonstrate it by testing its endpoints with a PostMan tool.

**Target Length:**
Roughly 900 to 1000 words

**Supporting Links:**
https://graphql.org/

**Comment by springframeworkguru** [comment]
Sounds interesting! Topic approved!

**Comment by vinod827** [comment]
It is done.
