### ISSUE TITLE
[POST] - How to setup Apache HTTP client connection pool

### ISSUE THREAD

**Issue by springframeworkguru** [spring-framework-guru/sfg-blog-posts#56]
For Spring RestTemplet and Apache HttpClient

Provide example project and explain how following config is used - 
```
@Configuration
public class RestTemplateConfig implements RestTemplateCustomizer {

    @Override
    public void customize(RestTemplate restTemplate) {

        PoolingHttpClientConnectionManager connManager
                = new PoolingHttpClientConnectionManager();
        connManager.setMaxTotal(20);
        connManager.setDefaultMaxPerRoute(5);

        restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory(HttpClients
                .custom().setConnectionManager(connManager).build()));
    }
}```

**Comment by Waginator** [comment]
I have set up a connection pool in my code examples for my post "Using RestTemplate with Apaches HttpClient", but I didn't use RestTemplateCustomizer for this. 

Please see the following classes:
- [ApacheHttpClientConfig](https://github.com/spring-framework-guru/sfg-blog-posts/blob/master/resttemplate/src/main/java/guru/springframework/resttemplate/config/ApacheHttpClientConfig.java)
- [RestTemplateConfig](https://github.com/spring-framework-guru/sfg-blog-posts/blob/master/resttemplate/src/main/java/guru/springframework/resttemplate/config/RestTemplateConfig.java) (Wiring of Apache HttpClient with RestTemplate)

@springframeworkguru 
Do you think we need a follow-up post for this or should I adjust my code?

**Comment by Waginator** [comment]
Done!

https://springframework.guru/using-resttemplate-with-apaches-httpclient/
