### ISSUE TITLE
[POST] - Java - Create Random Number

### ISSUE THREAD

**Issue by springframeworkguru** [spring-framework-guru/sfg-blog-posts#65]
Detailed post on creating random numbers in Java

**Comment by vinod827** [comment]
Hi John,

Can you please elaborate more about the requirement? What kind of random numbers are required?
Is it just by using Math.random() or anything special you are looking for?

Thanks

**Comment by springframeworkguru** [comment]
closing this one - just found I already have a post on this topic - published two years ago - woops!
