### ISSUE TITLE
 SFG Author Application - Jorge Tovar

### ISSUE THREAD

**Issue by jorgetovar** [spring-framework-guru/sfg-blog-posts#66]
**Jorge Tovar**

**Introduce yourself:**
I like to test programming languages and frameworks, currently interested on re-write some of your useful articles in Kotlin, with Reactive and Functional Programming.

Im a Systems Engineer and Magister in Information Technologies Architectures with more than five years of experience in Software Development. Currently focus on web development using technologies like Spring Boot, AWS, Java, Reactor, Angular, Maven, Ionic, etc. All the projects are executed in following agile principles based on Scrum and Xtreme Programming.

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/jorge-tovar-71847669/

**Comment by ximanta** [comment]
Hey Jorgetovar,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
