### ISSUE TITLE
[POST] - Using Ehcache in Spring Boot

### ISSUE THREAD

**Issue by Waginator** [spring-framework-guru/sfg-blog-posts#71]
**What Topic Would You Like To Write About:**
Ehcache is a free software for the implementation of caches in Java programs. It enables the conversion of local and distributed caches in main memory or on hard disks. This blog post is about using Ehcache 3 as Spring caching implementation. 

**Target Length:**
~1,500 Words

**Supporting Links:**
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html
https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#cache
https://spring.io/blog/2014/04/14/cache-abstraction-jcache-jsr-107-annotations-support
http://www.ehcache.org/documentation/3.0/

**Comment by springframeworkguru** [comment]
Great topic - approved!

**Comment by Waginator** [comment]
I'm done with this: https://springframework.guru/using-ehcache-3-in-spring-boot/
