### ISSUE TITLE
JDK 12 - the new 'switch' expression

### ISSUE THREAD

**Issue by vinod827** [spring-framework-guru/sfg-blog-posts#72]
The new JDK 12 has been released on March 2019. It has a new feature called **switch expression** which is quite different than the previous version of switch condition.
I would like to write an article showing various examples of writing switch by using JDK 12.

**Target Length:**
Approximately, 900 words

**Supporting Links:**
https://www.oracle.com/technetwork/java/javase/12-relnote-issues-5211422.html

**Comment by springframeworkguru** [comment]
Approved - sounds interesting!

**Comment by springframeworkguru** [comment]
May need to pause this one, or at least not merge to master. I'm not able to find a JDK 12 image for CircleCI. I'm sure it will be there soon - https://hub.docker.com/r/circleci/openjdk/tags

**Comment by ximanta** [comment]
Post added to wordpress. John need to check the CI issue.

**Comment by vinod827** [comment]
Okay
