### ISSUE TITLE
New Author Application

### ISSUE THREAD

**Issue by malvern** [spring-framework-guru/sfg-blog-posts#76]
**Your name:**
Malvern Dongeni

**Introduce yourself:**

I am a software developer skilled in enterprise systems development with more than two years of software development experience in various capacities.I have worked on a number of proprietary software development projects that include telecommunications USSD and VAS applications.
I hold a bachelor of Electronic Engineering Honours degree in Electronic engineering.I also hold the following certifications 0racle Certified Associate,Java SE 8 Programmer and Oracle Certified Professional,Java SE 8 Programmer.
I am more proficient in Java backend development using Spring,Spring Boot and Spring cloud, Junit, Mockito and Java SE desktop applications,JPA,Hibernate,SQL scripting and domain modelling.

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/malvern-dongeni-19081949/

**Comment by ximanta** [comment]
Hey Malvren,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
