### ISSUE TITLE
SFG Author Application

### ISSUE THREAD

**Issue by sweelam** [spring-framework-guru/sfg-blog-posts#79]
**Mohamed Sweelam**

Senior Java Developer specialized in developing business applications using Java and Javascript, I have been working for multiple years in different business scopes like Micro-finance, Banking, and Telecom.

I'm interested in Software Architectural Design for small and enterprise applications; and have sufficient background in different design techniques like Microservice, SOA and Monolithic design.

**Linkedin Profile**
https://www.linkedin.com/in/mohamedsweelam/

**Comment by ximanta** [comment]
Hey Sweelam,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
