### ISSUE TITLE
SFG Author Application

### ISSUE THREAD

**Issue by fame2105** [spring-framework-guru/sfg-blog-posts#83]
**Your name:**
Fame Issrani

**Introduce yourself:**
 I am an associate developer in Appdirect Pune. I am a holder of B.Tech degree in Computer Science. I also hold a certificate for AWS Solutions Architect - Associate. I want to learn and contribute to this community and It would be a great opportunity for me to be part of the spring framework guru authors family.

**Link to your LinkedIn Profile:**
https://www.linkedin.com/in/fame-issrani-54180084/

**Comment by ximanta** [comment]
Hey Fame,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
