### ISSUE TITLE
[POST] - Hikari Configuration for Spring Boot 2 and MySQL 

### ISSUE THREAD

**Issue by springframeworkguru** [spring-framework-guru/sfg-blog-posts#86]
There's a lot of poor and confusing information about configuring Hikari. Much of it is mixed in with pre-Spring Boot 2, or is no longer necessary. 

ie - much of this post is no longer needed: https://www.baeldung.com/hikaricp

Hikari has recommended configuration [for MySQL here](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration).

In the post please cover:
1. intro to Hikari
2. Cover it is now the default in Spring Boot 2.x +
3. Manual configuration is not needed - can be done with properties

Here is an example configuration:
```
spring.datasource.username=beer_service
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.useLocalSessionState=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
spring.datasource.hikari.data-source-properties.elideSetAutoCommits=true
spring.datasource.hikari.data-source-properties.maintainTimeStats=false

# Enable logging for config troubleshooting
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE 
```

Note the following:
* Configuration applies to MySQL [JDBC 4.x or higher only](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html). 
* Basic data source config
* Default Spring Boot properties ie ```spring.datasource.hikari.xxx```
* datasourceclass name is not needed, uses reflection - see [this link](https://github.com/brettwooldridge/HikariCP).
* Extended Hikari Datasource properties ie ```spring.datasource.hikari.data-source-properties.```
* Troubleshooting config - logging via last three statements

**Comment by Jouo** [comment]
Excuse me, do you know what Hikari means by the following?

**1)** Note: Spring Boot auto-configuration users, you need to use jdbcUrl-based configuration.
**2)** The MySQL DataSource is known to be broken with respect to network timeout support. Use jdbcUrl configuration instead.

It's just under "**_Popular DataSource Class Names_**" but I have no idea what they mean by those things
https://github.com/brettwooldridge/HikariCP

**Comment by tledwar** [comment]
> Excuse me @springframeworkguru , do you know what Hikari means by the following?
> 
> **1)** Note: Spring Boot auto-configuration users, you need to use jdbcUrl-based configuration.
> **2)** The MySQL DataSource is known to be broken with respect to network timeout support. Use jdbcUrl configuration instead.
> 
> It's just under "**_Popular DataSource Class Names_**" but I have no idea what they mean by those things
> https://github.com/brettwooldridge/HikariCP

I had to put spring.datasource.hikari.jdbc-url in my properties when using Spring Boot auto config. Without it, it would not connect.

**Comment by ximanta** [comment]
Post ready for publishing.
