### ISSUE TITLE
SFG Author Application

### ISSUE THREAD

**Issue by Diana254** [spring-framework-guru/sfg-blog-posts#89]
Diana Opiyo

Hi, I'm Diana. An experienced writer with interest in Programming languages and writing how to guides. I'm also a programming student and would love to share my knowledge with other students. I have 2 years experience with programming.

LinkedIn Profile Link: www.linkedin.com/in/diana-opiyo

**Comment by ximanta** [comment]
Hey Diana,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
