### ISSUE TITLE
Apply to be a SFG Author

### ISSUE THREAD

**Issue by Devil01** [spring-framework-guru/sfg-blog-posts#92]
**Navin Yadav**

** I am a Software Engineer having  3.5 years of experience in Java and Spring boot. My role is to Design, Coding, Unit testing, Documentation, etc. I have a keen interest in writing and sharing my learning through a blog While learning I came through SFG the content of SFG really help me to learn a lot related to Spring boot and design pattern, I have influenced with SFG blog. I want to be part of the SFG. Hoping for a positive response. 
Thanks,
Navin
**

**linkedin.com/in/navin-yadav-7a8828aa**

**Comment by ximanta** [comment]
Hey Navin,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
