### ISSUE TITLE
Pardeep Dureja

### ISSUE THREAD

**Issue by pdurejachd** [spring-framework-guru/sfg-blog-posts#93]
Pardeep Dureja

13+ Yrs of experience, worked majorly over core banking, eCommerce projects using java/jee, EJB mainly CMP, JSP/JSTL, spring, springboot, hibernate, quartz, MuleSoft, CloudFoundry  

Recent Article: https://dzone.com/articles/spring-boot-and-working-with-mbeans 

Linkedin Profile: www.linkedin.com/in/pardeep-73bb167
EmailID: pdurejachd@gmail.com

**Comment by ximanta** [comment]
Hey Pradeep,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
