### ISSUE TITLE
Application to be a SFG Author

### ISSUE THREAD

**Issue by taofcode** [spring-framework-guru/sfg-blog-posts#96]
Shelton Chiuswa

I am  software development junkie who has taught programming at various levels. I have	  in-depth experience in  Software development	 and	Solutions architecture,	web	and	 client application design, can	effectively  communicate  complex  technology concepts to audiences	of various levels.		

https://www.linkedin.com/in/shelton-chiuswa-4b786129/
[Shelton Chiuswa CV.pdf](https://github.com/spring-framework-guru/sfg-blog-posts/files/3847990/Shelton.Chiuswa.CV.pdf)

**Comment by ximanta** [comment]
Hey Shelton,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
