### ISSUE TITLE
Applying to be a Spring Framework Guru Author

### ISSUE THREAD

**Issue by RAJNISH3** [spring-framework-guru/sfg-blog-posts#97]
**RAJNISH TIWARI**

**Introduce yourself:**
9+ years of software development and has extensively worked on Java related topic be it Spring MVC, springboot as well  database-related technologies like SAP HANA, Kafka, noSQL, and postgresSQL.
**https://www.linkedin.com/in/rajnish-tiwari-03/:**
Few of my recent articles on various forums
> https://medium.com/@rajnishtiwari2010/conversion-of-json-to-parquet-format-using-apache-parquet-in-java-b694a0a7487d
> https://blog.sap-press.com/storing-iot-data-with-sap-hana
>https://blogs.sap.com/2019/09/09/spring-boot-app-to-covert-json-to-parquet-orc-csv-and-text-file-format-using-apache-spark-library/
> https://blogs.sap.com/2017/11/26/image-upload-retrieve-through-spring-restful-web-service-in-sap-cloud-platform/

**Comment by ximanta** [comment]
Hey Rajnish,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
