### ISSUE TITLE
SFG Author Application

### ISSUE THREAD

**Issue by fourgates** [spring-framework-guru/sfg-blog-posts#98]
**Phillip Ninan**

My name is Phillip Ninan and I am a senior software engineer at a software consulting company called [LBi Software](https://www.lbidynasty.com/). We have used the Spring framework since I have been there (over six years now). I frequently look to Spring Framework Guru when searching for solutions to Spring related issues. I am very excited about the opportunity to write for you and have some great ideas!

I have been the technical lead developer for several high profile MLB clients such as the Toronto Blue Jay's, the Philadelphia Philly's, and the Detroit Tigers. I was/am responsible for leading development on custom baseball scouting solutions for each one of these clubs. 

For any given project I have been responsible for setting up frameworks, core functionality, as well as the more complex modules that need to be implemented. I get the opportunity to make major improvements to our core framework every ~3 years. 

I mentor junior developers and spend a lot of time reviewing code. I try to promote good coding habits and have been responsible for helping develop our company's "Code of Conduct" for writing code and making pull requests. 

I attend conferences throughout the year to see what other developers are doing. My latest push for my team has been to write ADR's ([architectural design records](https://github.com/joelparkerhenderson/architecture_decision_record)) in an attempt to promote better habits when designing complex solutions. One mantra I preach to my teammates is that writing code should be the easy part, designing efficient and maintainable code is hard. 

I am a strong advocate of TDD programming. I have lead annual company workshops to help educate my co-workers on how TDD can help improve their quality of code, reduce bugs, and increase maintainability. The first year I lead this effort I was able to reduce server-side bugs by 24%. 

Most recently, I have been very interested in DevOps. I have made a very large push in my company to use Docker to containerize our applications. Using this approach has decreased our project onboarding by almost 90%. We have utilized [GitOps](https://www.weave.works/blog/what-is-gitops-really) and integrated containerization into our Jenkins CI/CD pipeline.  

**LinkedIn Profile:**
https://www.linkedin.com/in/phillip-ninan/

**Informal Blogging**
https://philbert2017.wordpress.com/

**Comment by ximanta** [comment]
Hey Philip,

Thanks for showing interest in contributing to Spring Framework Guru. 

Please share your e-mail ID to take this forward. You can send to ximanta.sarma@gmail.com

Thanks and Regards
Ximanta
